global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['your_server_ip:9323']

  - job_name: 'nginx-proxy-manager'
    static_configs:
      - targets: ['your_server_ip:81']

  - job_name: 'portainer'
    static_configs:
      - targets: ['your_server_ip:9443']

  - job_name: 'redis'
    static_configs:
      - targets: ['your_server_ip:6379']

  - job_name: 'forgejo'
    static_configs:
      - targets: ['your_server_ip:3000']
