---
- name: Check if Docker Compose executed successfully
  command: docker-compose -f {{ playbook_dir }}/docker-compose.yml ps
  args:
    chdir: "{{ playbook_dir }}"
  register: compose_status
  failed_when: "'Exit' in compose_status.stdout"
  changed_when: false

- name: Check if nginx-proxy-manager container is running
  docker_container:
    name: nginx-proxy-manager
    state: started
  failed_when: false

- name: Check if portainer container is running
  docker_container:
    name: portainer
    state: started
  failed_when: false

- name: Check if vaultwarden container is running
  docker_container:
    name: vaultwarden
    state: started
  failed_when: false

- name: Check if redis-stack-server container is running
  docker_container:
    name: redis-stack-server
    state: started
  failed_when: false

- name: Check if forgejo container is running
  docker_container:
    name: forgejo
    state: started
  failed_when: false

- name: Verify that Nginx Proxy Manager is accessible on port 80
  wait_for:
    host: "localhost"
    port: 80
    timeout: 10

- name: Verify that Portainer is accessible on port 9443
  wait_for:
    host: "localhost"
    port: 9443
    timeout: 10

- name: Verify that Vaultwarden is accessible on port 8080
  wait_for:
    host: "localhost"
    port: 8080
    timeout: 10

- name: Verify that Redis is accessible on port 6379
  wait_for:
    host: "localhost"
    port: 6379
    timeout: 10

- name: Verify that Forgejo is accessible on port 3000
  wait_for:
    host: "localhost"
    port: 3000
    timeout: 10

- name: Verify that Forgejo SSH is accessible on port 2222
  wait_for:
    host: "localhost"
    port: 2222
    timeout: 10

- name: Verify that Heimdall is accessible on port 8082
  wait_for:
    host: "localhost"
    port: 8082
    timeout: 10
