---
- name: Setup home server
  hosts: home_server
  become: true
  vars:
    playbook_dir: "{{ ansible_playbook_dir }}"
  roles:
    - initial_config
    - vsftpd
    - docker
    - check_docker_compose
    - monitoring
