---
- name: Update dnsmasq configuration
  hosts: all
  become: true
  tasks:
    - name: Add additional domains to dnsmasq configuration
      lineinfile:
        path: /etc/dnsmasq.conf
        line: "server=/newdomain.com/8.8.8.8"
        state: present

    - name: Add additional domains to dnsmasq configuration
      lineinfile:
        path: /etc/dnsmasq.conf
        line: "server=/newdomain.com/8.8.4.4"
        state: present

    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
